### ISSUE TITLE
Error raised during running ekf_example.ipynb

### ISSUE THREAD

**Issue by alecwangcq** [EEA-sensors/parallel-non-linear-gaussian-smoothers#7]
Hi Adrien,

I am experimenting with your implementation of EKF at https://github.com/EEA-sensors/parallel-non-linear-gaussian-smoothers . When I run the demo at https://github.com/EEA-sensors/parallel-non-linear-gaussian-smoothers/blob/master/notebooks/ekf_example.ipynb , I got the following error,

`Traceback (most recent call last):
  File "test.py", line 41, in <module>
    initial_states.mean)
  File "/Users/ahhhhh/Projects/libs/parallel-non-linear-gaussian-smoothers/parsmooth/sequential/extended.py", line 171, in filter_routine
    filtered_states)
  File "/Users/ahhhhh/anaconda3/envs/i2c/lib/python3.7/site-packages/jax/tree_util.py", line 185, in tree_map
    leaves, treedef = tree_flatten(tree, is_leaf)
  File "/Users/ahhhhh/anaconda3/envs/i2c/lib/python3.7/site-packages/jax/tree_util.py", line 68, in tree_flatten
    return pytree.flatten(tree, is_leaf)
TypeError: flatten(): incompatible function arguments. The following argument types are supported:
    1. (tree: handle, leaf_predicate: Optional[function] = None) -> Tuple[List[object], xla::PyTreeDef]

Invoked with: MVNormalParameters(mean=DeviceArray([-1., -1.,  0.,  0.,  0.], dtype=float32), cov=DeviceArray([[1., 0., 0., 0., 0.],
             [0., 1., 0., 0., 0.],
             [0., 0., 1., 0., 0.],
             [0., 0., 0., 1., 0.],
             [0., 0., 0., 0., 1.]], dtype=float32)), MVNormalParameters(mean=DeviceArray([[ 0.24840665,  0.09308386,  0.01248344,  0.01093029,
               0.        ],
             [ 0.03746383,  0.23410054,  0.00508429,  0.01827998,
               0.        ],
             [ 0.23771721,  0.30913222,  0.01687567,  0.02287539,
               0.        ],
             ...,
             [ 4.557808  , -0.6450761 ,  0.34732455, -0.02336112,
               0.        ],
             [ 4.5395474 , -0.63547087,  0.33096   , -0.01337144,
               0.        ],
             [ 4.5341086 , -0.6309036 ,  0.32432666, -0.00870017,
               0.        ]], dtype=float32), cov=DeviceArray([[[4.80470479e-01, 7.26313218e-02, 4.80446499e-03,
               7.26276892e-04, 0.00000000e+00],
              [7.26313218e-02, 3.01685572e-01, 7.26276543e-04,
               3.01670423e-03, 0.00000000e+00],
              [4.80446499e-03, 7.26276543e-04, 1.00004804e+00,
               7.26240160e-06, 0.00000000e+00],
              [7.26276892e-04, 3.01670423e-03, 7.26240160e-06,
               1.00003016e+00, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 1.00100005e+00]],

             [[3.18968415e-01, 5.64138964e-02, 9.78219602e-03,
               8.46176874e-04, 0.00000000e+00],
              [5.64138964e-02, 1.80103362e-01, 8.46176350e-04,
               7.69929867e-03, 0.00000000e+00],
              [9.78219602e-03, 8.46176350e-04, 9.99988794e-01,
               3.86797037e-05, 0.00000000e+00],
              [8.46176874e-04, 7.69929867e-03, 3.86797037e-05,
               9.99893546e-01, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 1.00200009e+00]],

             [[2.39024982e-01, 4.48005982e-02, 1.47710275e-02,
               8.96678015e-04, 0.00000000e+00],
              [4.48005982e-02, 1.28746539e-01, 8.96677608e-04,
               1.25638191e-02, 0.00000000e+00],
              [1.47710275e-02, 8.96677608e-04, 9.99763727e-01,
               1.21788929e-04, 0.00000000e+00],
              [8.96678015e-04, 1.25638191e-02, 1.21788929e-04,
               9.99463916e-01, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 1.00300014e+00]],

             ...,

             [[1.34674460e-02, 2.36830069e-03, 9.61379707e-03,
               1.24140584e-03, 0.00000000e+00],
              [2.36830069e-03, 7.63776246e-03, 1.24140491e-03,
               6.55802153e-03, 0.00000000e+00],
              [9.61379707e-03, 1.24140491e-03, 1.38314553e-02,
               9.83629958e-04, 0.00000000e+00],
              [1.24140584e-03, 6.55802153e-03, 9.83629958e-04,
               1.14102429e-02, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 1.99804664e+00]],

             [[1.34674460e-02, 2.36830069e-03, 9.61379707e-03,
               1.24140584e-03, 0.00000000e+00],
              [2.36830069e-03, 7.63776246e-03, 1.24140491e-03,
               6.55802153e-03, 0.00000000e+00],
              [9.61379707e-03, 1.24140491e-03, 1.38314543e-02,
               9.83629841e-04, 0.00000000e+00],
              [1.24140584e-03, 6.55802153e-03, 9.83629841e-04,
               1.14102429e-02, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 1.99904668e+00]],

             [[1.34674460e-02, 2.36830069e-03, 9.61379707e-03,
               1.24140584e-03, 0.00000000e+00],
              [2.36830069e-03, 7.63776246e-03, 1.24140491e-03,
               6.55802153e-03, 0.00000000e+00],
              [9.61379707e-03, 1.24140491e-03, 1.38314534e-02,
               9.83629725e-04, 0.00000000e+00],
              [1.24140584e-03, 6.55802153e-03, 9.83629725e-04,
               1.14102429e-02, 0.00000000e+00],
              [0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
               0.00000000e+00, 2.00004673e+00]]], dtype=float32))`

I am running on a Macbook M1 and my jax (cpu) version is 0.2.10.

**Comment by AdrienCorenflos** [comment]
Hi,

I managed to run it with JAX v0.3.4, maybe just update your JAX version?

**Comment by alecwangcq** [comment]
Thank you. I finally made it to install the latest version of Jax on MacBook M1 with macOS 12.01... The error is resolved. I am wondering why the older version of Jax will raise the error when doing the tree_map?
